= Loket.NET
:keywords: bsa-pdam,loket

== Overview

Loket.NET merupakan salah satu _desktop app_ (module) SiPDAMPintar yang di-_revamp_ dari Loket versi Delphi dengan beberapa _improvement UI/UX_.

== Team Involved

Berikut adalah _talent_ yang terlibat dalam pengembangan sistem Loket.NET. Masing-masing sudah dilengkapi dengan alamat _email_ yang bisa dihubungi jika diperlukan.


|===
| *Name* | *Role* | *Email* 
| Aryo Indrasmoro | Engineering Manager | aryo@alterra.id
| Acep Zulkipli J | Development Team Lead | azul@alterra.id
| Ahmad Alfan | Software Engineer | alfan@alterra.id
| Angga Dwi Apria Rifandi | Software Engineer | angga@alterra.id
| Aulia Rahman Hanifan | Software Engineer | ahanifan@alterra.id
| I Nyoman Widiarta | Software Engineer | widiarta@bsa.id
| Josua Geovani Sinaga | Software Engineer | josua.sinaga@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<docs/architecture-loket.adoc#, Architecture Loket.NET>>

<<docs/technology-loket.adoc#, Technology Loket.NET>>

<<docs/environment-loket.adoc#, Environment Loket.NET>>

<<docs/database-loket.adoc#, Database Documentation Loket.NET>>

<<docs/release-deploy-loket.adoc#, Release and Deployment Loket.NET>>

<<docs/flow-wire-loket.adoc#, Flow and Wireframe Loket.NET>>

== Onboarding Information

<<docs/dev-onboarding-loket.adoc#, Developer Onboarding Loket.NET>>

<<docs/development-loket.adoc#, Development Loket.NET>>

<<docs/naming-convention-loket.adoc#, Naming Convention Loket.NET>>

== Documentation

Berikut adalah dokumen penunjang untuk penggunaan sistem baik Loket versi Delphi maupun Loket.NET :

<<docs/product-information-loket.adoc#, Product Information Document Loket Delphi>>

https://github.com/bimasaktialterra/loket.net/blob/main/CHANGELOG.md[Release Note Loket.NET]

